feat: implemented signIn/signUp endpoints and jwt endpoint auth
david-de-angelis/nAPI pull request #2
Opened 2022-04-04 07:35 UTC by 00Chaotic

This change implements the `signIn` and `signUp` graphql endpoints using JWTs. I have tried sticking to the current file/code structure, and have tried keeping lists (e.g. JSON object fields spanning multiple lines) in alphabetical order.

The `signIn` endpoint was created under the assumption that users would be using an email/password combination to sign in.
The `signUp` endpoint is quite bare right now, and may need more changes like validation of additional fields.

### Notes
- Both `signIn` _and_ `signUp` endpoints return a JWT token on successful execution, removing the need for clients to sign in right after signing up
- Default JWT expiration is set to 1 day (managed by env var `JWT_EXPIRES_IN`)
- Users must use the signIn endpoint to receive a JWT token, which will need to be included in an `Authorization` header with each request in the `Bearer <token>` format
- This piece of functionality uses [Argon2](https://www.npmjs.com/package/argon2) as its password hashing library

2022-04-04 07:39 UTC, 00Chaotic commented on package.json
> +    "seed": "ts-node --compiler-options {\\\"module\\\":\\\"CommonJS\\\"} src/model/seed.mjs"
This change may differ per terminal due to (from my understanding) the way flags are passed; in my case, I needed to "escape the escape characters" but I cannot guarantee that this will work for everyone.

2022-04-04 07:40 UTC, 00Chaotic commented on src/controller/resolvers/userResolver.js
> +        // TODO anything else needed here?
Worth looking at whether anything else is needed here

2022-04-11 14:37 UTC, david-de-angelis requested changes

2022-04-11 14:37 UTC, david-de-angelis commented on src/controller/authorisation/permissions.js
> +  User: allow,
is setting User to 'allow' mandatory? seems like we would be exposing email addresses etc.

2022-04-11 14:37 UTC, david-de-angelis commented on src/controller/context.js
> +        return session;
what is the format of this session object? out of curiousity, is it just a user object, a userid, or what?

2022-04-11 14:37 UTC, david-de-angelis commented on src/controller/resolvers/userResolver.js
> +        // TODO anything else needed here?
should be good for now, can't think of anything else that we would currently need

2022-04-11 14:37 UTC, david-de-angelis commented on src/controller/resolvers/userResolver.js
> +                return {error: "Error hashing password: " + err};
probably check that 'err' doesnt return args.password somwhere in the stringified form

2022-04-11 14:37 UTC, david-de-angelis commented on src/controller/resolvers/userResolver.js
> +                newUser = await context.db.user.create({
hm, we should maybe check to see if the user exists first, however the uniqueness constraint on the 'email' field will fail anyway, 

might also be worth adding in a regex condition to see if the email format is correct

2022-04-11 14:37 UTC, david-de-angelis commented on src/controller/schema/user.js
> +
good stuff :)

2022-04-11 14:37 UTC, david-de-angelis commented on src/model/migrations/20220329140545_init/migration.sql
> +    "email" TEXT NOT NULL,
**!!! Attention specifically needed here !!!**
did you manually create this file? unless there has been a strange bug, i would assume so

this migration has already occurred, and as such changing previously applied migrations can have unintended consequences, please use Prisma Migrate' to create a new migration to implement the new User fields.

2022-04-12 09:20 UTC, 00Chaotic commented on src/controller/context.js
> +        return session;
It returns the decoded jwt payload, which is currently an object with user id and role (which might change once I refactor the code to better reflect the ERD).
Function docs: https://www.npmjs.com/package/jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

2022-04-12 09:28 UTC, 00Chaotic commented on src/model/migrations/20220329140545_init/migration.sql
> +    "email" TEXT NOT NULL,
Ah yeah this was manually created, was unaware about that. Will fix.

2022-04-12 09:46 UTC, david-de-angelis commented on src/controller/context.js
> +        return session;
cool - cheers

2022-04-12 09:47 UTC, david-de-angelis commented on src/controller/resolvers/userResolver.js
> +                return {error: "Error hashing password: " + err};
can leave it for now 👍

2022-04-12 09:49 UTC, david-de-angelis commented on src/controller/resolvers/userResolver.js
> +                newUser = await context.db.user.create({
@00Chaotic, that could be achieved by something like this:

```
try {
  some_function(); // may throw three types of exceptions
} catch (e) {
  if (e instanceof TypeError) {
    // statements to handle TypeError exceptions
  } else if (e instanceof RangeError) {
    // statements to handle RangeError exceptions
  } else if (e instanceof EvalError) {
    // statements to handle EvalError exceptions
  } else {
    // statements to handle any unspecified exceptions
  }
}
```

2022-04-12 09:49 UTC, david-de-angelis commented on src/model/migrations/20220329140545_init/migration.sql
> +    "email" TEXT NOT NULL,
Thanks :)

2022-04-12 10:27 UTC, 00Chaotic commented on src/controller/authorisation/permissions.js
> +  User: allow,
Ah okay, so that's the permission for the User **type/object** rather than the exported User file/handler. Got it, will fix.

2022-04-13 21:55 UTC, david-de-angelis approved these changes
good work Jaffar!

2022-04-13 21:55 UTC, merged